config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout' }
  authenticate(:user, ->(user) { user.is_admin }) { mount Sidekiq::Web => '/sidekiq' }
  resources :categories, except: %i[show]
  resources :reservations, except: %i[show] do
    post :change_status
  end
  resources :books, except: %i[show] do
    collection do
      get :download_csv_template, defaults: { format: 'csv' }
      get :import
      post :import_file
    end
  end

  root 'home#index'
  get 'dashboard', to: 'home#dashboard'
  post :clean_all_notifications, to: 'notifications#clean_all'
  post '/:id/clean_notification', to: 'notifications#clean', as: :clean_notification
end

app/models/book.rb
require 'csv'

class Book < ApplicationRecord
  validates_presence_of :title, :author
  validates :title, uniqueness: true
  belongs_to :category
  has_many :reservations, dependent: :destroy
  after_create :send_notification
  extend ExportCsv

  EXPORT_CSV = %w[id title author category_id].freeze
  CHANGE_ATTRS = { user_id: 'user.name', category_id: 'category_name' }.freeze

  IMPORT_CSV = [
    I18n.t('activerecord.attributes.book.title'),
    I18n.t('activerecord.attributes.book.author'),
    "Id #{I18n.t('activerecord.attributes.book.category_id')}"
  ].freeze

  def category_name
    category.name
  end

  def self.save_file_on_server(file, user_id)
    folder = File.join(Rails.root.join('tmp', 'imports'))
    FileUtils.mkdir_p(folder) unless Dir.exist?(folder)

    filename = "#{SecureRandom.alphanumeric(10)}-import-books.csv"
    path = File.join(folder, filename)

    File.open(path, 'wb') { |f| f.write(CSV.parse(file)) }
    ImportCsvWorker.perform_async(filename, user_id)
  end

  def send_notification
    SendNotificationWorker.perform_async(self.id)
  end

  ransacker :created_at do
    Arel.sql('date(created_at)')
  end

  ransacker :updated_at do
    Arel.sql('date(updated_at)')
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ edit update destroy ]
  before_action :set_objects_to_select, only: %i[ index new edit create update ]

  def index   
    respond_to do |format|
      format.html do
        @q = Book.includes(:category).order(:title).ransack(params[:q])
        @pagy, @books = pagy(@q.result)
      end
      format.csv { send_data Book.as_csv }
    end
  end

  def new
    @book = Book.new
  end

  def edit; end

  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to books_path, flash: { notice: I18n.t('successfully_created', model: I18n.t('activerecord.models.book.one')) }}
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to books_path, notice: I18n.t('successfully_updated', model: I18n.t('activerecord.models.book.one')) }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: I18n.t('successfully_destroyed', model: I18n.t('activerecord.models.book.one')) }
    end
  end

  def download_csv_template
    csv_string = generate_csv(Book::IMPORT_CSV)
    respond_to do |format|
      format.csv do
        send_data "\uFEFF" + csv_string, type: :csv, filename: 'books_template.csv'
      end
    end
  end

  def import; end

  def import_file
    Book.save_file_on_server(params[:file].tempfile, current_user.id)
    redirect_to import_books_path, notice: I18n.t('import_is_being_processed')
  end

  private

  def set_book
    @book = Book.includes(:category).find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :author, :category_id)
  end

  def set_objects_to_select
    @categories = Category.select(:id, :name).order(:name)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.haml
= render 'shared/breadcrumb', index_name: I18n.t('activerecord.models.book.other'), index_path: books_path, new_name: nil
= form_for @book do |f|
  = render "shared/error_messages", resource: @book
  .row
    .col-6
      .form-group
        = f.label :title, class: 'form-label'
        = f.text_field :title, maxlength: 25, class: 'form-control'
      .form-group
        = f.label :author, class: 'form-label'
        = f.text_field :author, maxlength: 25, class: 'form-control'
      .form-group
        = f.label :category_id, class: 'form-label'
        = f.collection_select :category_id, @categories, :id, :name, {}, class: 'form-control'
      .form-group
        = f.submit class: 'btn btn-outline-secondary'

app/views/books/edit.html.haml
= render 'form'

app/views/books/import.html.haml
= render 'shared/breadcrumb', index_name: I18n.t('import_books'), index_path: import_books_path, new_name: nil
= form_tag import_file_books_path, multipart: true do
  .row 
    .col-md-3
      = link_to download_csv_template_books_path, class: 'btn btn-sm btn-theme' do
        %i.fas.fa-download.fa-sm.text-dark-50
        Template Csv
  %br
  .row
    .col-6.d-flex
      = file_field_tag :file, class: 'form-control', accept: '.csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel'
      = submit_tag I18n.t('import_csv'), class: 'btn btn-sm btn-theme mx-1'

app/views/books/index.html.haml
= render 'shared/breadcrumb', index_name: I18n.t('activerecord.models.book.other'), index_path: books_path, new_name: I18n.t('register_book'), new_path: new_book_path
.row
  .col-3
    = search_form_for @q, class: 'd-none d-sm-inline-block form-inline mr-auto w-100 navbar-search' do |f|
      .input-group.mb-2
        = f.search_field :title_i_cont, class: 'form-control bg-white border-1 small', placeholder: I18n.t('activerecord.attributes.book.title')
      .input-group.mb-2
        = f.search_field :author_i_cont, class: 'form-control bg-white border-1 small', placeholder: I18n.t('activerecord.attributes.book.author')
      .input-group.mb-2
        = f.search_field :created_at_date_equals, placeholder: I18n.t('activerecord.attributes.book.created_at'), class: 'form-control bg-white border-1 small'
      .input-group.mb-2
        = f.search_field :updated_at_date_equals, placeholder: I18n.t('activerecord.attributes.book.updated_at'), class: 'form-control bg-white border-1 small'
      .input-group
        = f.collection_select :category_id_eq, @categories, :id, :name, { include_blank: I18n.t('select_category') }, class: 'form-control bg-white border-1 small'
      .mt-2
        %button.btn.btn-theme{ type: 'submit' }
          %i.fas.fa-search.fa-sm
        = link_to books_path, class: 'btn btn-theme' do
          %i.fa.fa-x
      
  .col-9
    - if @books.size.zero?
      %h3.text-center= I18n.t('no_books')
    -else
      %table.table.table-hover.table-striped.text-center
        %thead
          %tr.table-top
            %th.w-th= I18n.t('activerecord.attributes.book.title')
            %th.w-th= I18n.t('activerecord.attributes.book.author')
            %th.w-th= I18n.t('activerecord.attributes.book.category_id')
            %th.w-th= I18n.t('activerecord.attributes.book.created_at')
            %th.w-th= I18n.t('activerecord.attributes.book.updated_at')
            - if current_user.is_admin
              %th
              %th
              %th
        %tbody
          - @books.each do |book|
            %tr
              %td
                .break-text{ title: book.title }= book.title
              %td
                .break-text{ title: book.author }= book.author
              %td
                .break-text{ title: book.category_name }= book.category_name
              %td
                .break-text{ title: book.created_at.to_date }= I18n.l(book.created_at.to_date)
              %td
                .break-text{ title: book.updated_at.to_date }= I18n.l(book.updated_at.to_date)
              - if current_user.is_admin
                %td= link_to set_button('pen-to-square', I18n.t('edit'), 'secondary'), edit_book_path(book)
                %td= link_to set_button('xmark', I18n.t('delete'), 'danger'), book, method: :delete, data: { confirm: I18n.t('confirm_delete_book') }
                %td
      != pagy_bootstrap_nav(@pagy)

app/views/books/new.html.haml
= render 'form'