config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout' }
  authenticate(:user, ->(user) { user.is_admin }) { mount Sidekiq::Web => '/sidekiq' }
  resources :categories, except: %i[show]
  resources :reservations, except: %i[show] do
    post :change_status
  end
  resources :books, except: %i[show] do
    collection do
      get :download_csv_template, defaults: { format: 'csv' }
      get :import
      post :import_file
    end
  end

  root 'home#index'
  get 'dashboard', to: 'home#dashboard'
  post :clean_all_notifications, to: 'notifications#clean_all'
  post '/:id/clean_notification', to: 'notifications#clean', as: :clean_notification
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  validates_presence_of :booking_date, :return_date
  validate :validate_dates
  belongs_to :user
  belongs_to :book
  extend ExportCsv

  EXPORT_CSV = %w[id user_id book_id booking_date return_date].freeze
  CHANGE_ATTRS = {			
    user_id: 'user_name',
    book_id: 'book_title',
    booking_date: 'booking_date_formated',
    return_date: 'return_date_formated'
  }.freeze

  enum booking_status: { opened: 0, finished: 1 }

  ransacker :booking_date do
    Arel.sql('date(booking_date)')
  end

  ransacker :return_date do
    Arel.sql('date(return_date)')
  end

  def user_name
    user.name
  end

  def book_title
    book.title
  end
  
  def self.human_booking_statuses
    booking_statuses.map{ |k, v| [human_enum(k), v] }
  end

  def booking_date_formated
    I18n.l(booking_date.to_date)
  end

  def return_date_formated
    I18n.l(return_date.to_date)
  end

  def validate_dates
    if self.booking_date.present? && self.return_date.present?
      self.errors.add(:booking_date, I18n.t('errors.invalide_date')) if self.booking_date > self.return_date
    end
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: %i[ edit update destroy change_status ]
  before_action :set_objects_to_select, only: %i[ index new edit create update ]

  def index
    respond_to do |format|
      format.html do
        params[:q] = params[:q]&.merge(user_id_eq: current_user.id) || { user_id_eq: current_user.id } unless current_user.is_admin
        @q = Reservation.includes(:user, :book).order(:id).ransack(params[:q])
        @pagy, @reservations = pagy(@q.result)
      end
      format.csv { send_data Reservation.as_csv }
    end
  end

  def new
    @reservation = Reservation.new
  end

  def edit; end

  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to reservations_path, notice: I18n.t('successfully_created', model: I18n.t('activerecord.models.reservation.one')) }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to reservations_path, notice: I18n.t('successfully_updated', model: I18n.t('activerecord.models.reservation.one')) }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @reservation.destroy

    respond_to do |format|
      format.html { redirect_to reservations_url, notice: I18n.t('successfully_destroyed', model: I18n.t('activerecord.models.reservation.one')) }
    end
  end

  def change_status
    @reservation.opened? ? @reservation.finished! : @reservation.opened!
    redirect_to reservations_path(q: query_params), notice: I18n.t('booking_status_updated')
  end

  private

  def set_reservation
    @reservation = Reservation.find(params[:id] || params[:reservation_id])
  end

  def reservation_params
    params.require(:reservation).permit(:user_id, :book_id, :booking_date, :return_date, :booking_status)
  end

  def query_params
    params.require(:q).permit(:booking_date_date_equals, :return_date_date_equals, :user_id_eq, :book_id_eq, :booking_status_eq)
  end

  def set_objects_to_select
    @users = User.select(:id, :name).where(is_admin: false).order(:name)
    @books = Book.select(:id, :title).order(:title)
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.haml
= render 'shared/breadcrumb', index_name: I18n.t('activerecord.models.reservation.other'), index_path: reservations_path, new_name: nil
= form_for @reservation do |f|
  = render "shared/error_messages", resource: @reservation
  .row
    .col-4
      - if current_user.is_admin
        .form-group
          = f.label :user_id, class: 'form-label'
          = f.collection_select :user_id, @users, :id, :name, {}, class: 'form-control'
      - else
        = f.hidden_field :user_id, value: current_user.id
      .form-group
        = f.label :book_id, class: 'form-label'
        = f.collection_select :book_id, @books, :id, :title, {}, class: 'form-control'
      .form-group
        = f.label :booking_date, class: 'form-label'
        = f.date_field :booking_date, class: 'form-control'
      .form-group
        = f.label :return_date, class: 'form-label'
        = f.date_field :return_date, class: 'form-control'
      .form-group
        = f.submit class: 'btn btn-outline-secondary'

app/views/reservations/edit.html.haml
= render 'form'

app/views/reservations/index.html.haml
= render 'shared/breadcrumb', index_name: I18n.t('activerecord.models.reservation.other'), index_path: reservations_path, new_name: I18n.t('register_reservation'), new_path: new_reservation_path
.row
  .col-3
    = search_form_for @q, class: 'd-none d-sm-inline-block form-inline mr-auto w-100 navbar-search' do |f|
      .input-group.mb-2
        = f.search_field :booking_date_date_equals, placeholder: I18n.t('activerecord.attributes.reservation.booking_date'), class: 'form-control bg-white border-1 small'
      .input-group.mb-2
        = f.search_field :return_date_date_equals, placeholder: I18n.t('activerecord.attributes.reservation.return_date'), class: 'form-control bg-white border-1 small'
      - if current_user.is_admin
        .input-group.mb-2
          = f.collection_select :user_id_eq, @users, :id, :name, { include_blank: I18n.t('select_user') }, class: 'form-control bg-white border-1 small'
      .input-group.mb-2
        = f.collection_select :book_id_eq, @books, :id, :title, { include_blank: I18n.t('select_book') }, class: 'form-control bg-white border-1 small'
      .input-group.mb-2
        = f.collection_select :booking_status_eq,  Reservation.human_booking_statuses, :last, :first, { include_blank: I18n.t('activerecord.attributes.reservation.booking_status') }, class: 'form-control bg-white border-1 small'
      .mt-2
        %button.btn.btn-theme{ type: 'submit' }
          %i.fas.fa-search.fa-sm
        = link_to reservations_path, class: 'btn btn-theme' do
          %i.fa.fa-x
  .col-9
    - if @reservations.size.zero?
      %h3.text-center= I18n.t('no_reservations')
    -else
      %table.table.table-hover.table-striped.text-center
        %thead
          %tr.table-top
            - if current_user.is_admin
              %th.w-th= I18n.t('activerecord.attributes.reservation.user_id')
            %th.w-th= I18n.t('activerecord.attributes.reservation.book_id')
            %th.w-th= I18n.t('activerecord.attributes.reservation.booking_date')
            %th.w-th= I18n.t('activerecord.attributes.reservation.return_date')
            %th.w-th= I18n.t('activerecord.attributes.reservation.booking_status')
            - if current_user.is_admin
              %th
              %th
              %th
              %th
        %tbody
          - @reservations.each do |reservation|
            %tr
              - if current_user.is_admin
                %td
                  .break-text{ title: reservation.user_name }= reservation.user_name
              %td
                .break-text{ title: reservation.book_title }= reservation.book_title
              %td
                .break-text{ title: reservation.booking_date_formated }= reservation.booking_date_formated
              %td
                .break-text{ title: reservation.return_date_formated }= reservation.return_date_formated
              %td
                .break-text= Reservation.human_enum(reservation.booking_status)
              - if current_user.is_admin
                %td= link_to set_button('arrows-rotate', I18n.t('change_status'), 'success'), set_query_to_change(reservation.id), method: :post
                %td= link_to set_button('pen-to-square', I18n.t('edit'), 'dark'), edit_reservation_path(reservation)
                %td= link_to set_button('xmark', I18n.t('delete'), 'danger'), reservation, method: :delete, data: { confirm: I18n.t('confirm_delete') }
                %td
      != pagy_bootstrap_nav(@pagy)

app/views/reservations/new.html.haml
= render 'form'