config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout' }
  authenticate(:user, ->(user) { user.is_admin }) { mount Sidekiq::Web => '/sidekiq' }
  resources :categories, except: %i[show]
  resources :reservations, except: %i[show] do
    post :change_status
  end
  resources :books, except: %i[show] do
    collection do
      get :download_csv_template, defaults: { format: 'csv' }
      get :import
      post :import_file
    end
  end

  root 'home#index'
  get 'dashboard', to: 'home#dashboard'
  post :clean_all_notifications, to: 'notifications#clean_all'
  post '/:id/clean_notification', to: 'notifications#clean', as: :clean_notification
end

app/models/category.rb
class Category < ApplicationRecord
	validates :name, uniqueness: true
	has_many :books, dependent: :destroy
	extend ExportCsv

  EXPORT_CSV = %w[id name].freeze
	CHANGE_ATTRS = {}.freeze
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ edit update destroy ]

  def index
    respond_to do |format|
      format.html do
        @q = Category.order(:id).ransack(params[:q])
        @pagy, @categories = pagy(@q.result)
      end
      format.csv { send_data Category.as_csv }
    end
  end

  def new
    @category = Category.new
  end

  def edit; end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: I18n.t('successfully_created', model: I18n.t('activerecord.models.category.one')) }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_path, notice: I18n.t('successfully_updated', model: I18n.t('activerecord.models.category.one')) }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: I18n.t('successfully_destroyed', model: I18n.t('activerecord.models.category.one')) }
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.haml
= render 'shared/breadcrumb', index_name: I18n.t('activerecord.models.category.other'), index_path: categories_path, new_name: nil
= form_for @category do |f|
  = render "shared/error_messages", resource: @category
  .row
    .col-3
      .form-group
        = f.label :name, class: 'form-label'
        = f.text_field :name, maxlength: 20, class: 'form-control'
      .form-group
        = f.submit class: 'btn btn-outline-secondary'

app/views/categories/edit.html.haml
= render 'form'

app/views/categories/index.html.haml
= render 'shared/breadcrumb', index_name: I18n.t('activerecord.models.category.other'), index_path: categories_path, new_name: I18n.t('register_category'), new_path: new_category_path

.row
  .col-3
    = search_form_for @q, class: 'd-none d-sm-inline-block form-inline mr-auto w-100 navbar-search' do |f|
      .input-group.mb-2
        = f.search_field :name_i_cont, class: 'form-control bg-white border-1 small', placeholder: I18n.t('activerecord.attributes.category.name')
      .mt-2
        %button.btn.btn-theme{ type: 'submit' }
          %i.fas.fa-search.fa-sm
        = link_to categories_path, class: 'btn btn-theme' do
          %i.fa.fa-x
  .col-9
    - if @categories.size.zero?
      %h3.text-center= I18n.t('no_categories')
    -else
      %table.table.table-hover.table-striped.text-center
        %thead
          %tr.table-top
            %th Id
            %th{ style: 'width: 50%;' }= I18n.t('activerecord.attributes.category.name')
            %th
            %th

        %tbody
          - @categories.each do |category|
            %tr
              %td= category.id
              %td= category.name
              %td= link_to set_button('pen-to-square', I18n.t('edit'), 'secondary'), edit_category_path(category)
              %td= link_to set_button('xmark', I18n.t('delete'), 'danger'), category, method: :delete, data: { confirm: I18n.t('confirm_delete_category') }
      != pagy_bootstrap_nav(@pagy)

app/views/categories/new.html.haml
= render 'form'