config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout' }
  authenticate(:user, ->(user) { user.is_admin }) { mount Sidekiq::Web => '/sidekiq' }
  resources :categories, except: %i[show]
  resources :reservations, except: %i[show] do
    post :change_status
  end
  resources :books, except: %i[show] do
    collection do
      get :download_csv_template, defaults: { format: 'csv' }
      get :import
      post :import_file
    end
  end

  root 'home#index'
  get 'dashboard', to: 'home#dashboard'
  post :clean_all_notifications, to: 'notifications#clean_all'
  post '/:id/clean_notification', to: 'notifications#clean', as: :clean_notification
end

app/views/layouts/_footer.html.haml
%footer.sticky-footer.bg-white
	.container.my-auto
		.copyright.text-center.my-auto
			%span Copyright © Book Reservation 2022

app/views/layouts/_scroll_top.html.haml
%a.scroll-to-top.rounded{ href: '#page-top' }
	%i.fas.fa-angle-up

app/views/layouts/_sidebar.html.haml
%ul#accordionSidebar.navbar-nav.bg-gradient-primary.sidebar.sidebar-dark.accordion{ class: sidebar_class }
  = link_to root_path, class: 'sidebar-brand d-flex align-items-center justify-content-center' do
    .sidebar-brand-icon.rotate-n-15
      %i.fa.fa-book-atlas
    .sidebar-brand-text.mx-3
      book
      %br
      %sup system
  %hr.sidebar-divider.my-0
  - if current_user.is_admin
    %li.nav-item
      = link_to dashboard_path, class: 'nav-link' do
        %i.fas.fa-fw.fa-tachometer-alt
        %span Dashboard
    %li.nav-item
      = link_to new_user_registration_path, class: 'nav-link' do
        %i.fa.fa-user-plus
        %span= I18n.t('new_user')
  %li.nav-item
    %a.nav-link.collapsed{'aria-controls': 'collapseBooks', 'aria-expanded': 'true', 'data-bs-target': '#collapseBooks', 'data-bs-toggle': 'collapse', href: '#'}
      %i.fa.fa-book-open
      %span= I18n.t('activerecord.models.book.other')
    #collapseBooks.collapse{'aria-labelledby': 'headingUtilities', 'data-bs-parent': '#accordionSidebar'}
      .bg-white.py-2.collapse-inner.rounded
        = link_to I18n.t('register_book'), new_book_path, class: 'collapse-item' if current_user.is_admin
        = link_to I18n.t('view_all'), books_path, class: 'collapse-item'
  %li.nav-item
    %a.nav-link.collapsed{'aria-controls': 'collapseReservations', 'aria-expanded': 'true', 'data-bs-target': '#collapseReservations', 'data-bs-toggle': 'collapse', href: '#'}
      %i.fa.fa-calendar-days
      %span= I18n.t('activerecord.models.reservation.other')
    #collapseReservations.collapse{'aria-labelledby': 'headingPages', 'data-bs-parent': '#accordionSidebar'}
      .bg-white.py-2.collapse-inner.rounded
        = link_to I18n.t('register_reservation'), new_reservation_path, class: 'collapse-item'
        = link_to I18n.t('view_all'), reservations_path, class: 'collapse-item'
  - if current_user.is_admin
    %li.nav-item
      %a.nav-link.collapsed{'aria-controls': 'collapseCategories', 'aria-expanded': 'true', 'data-bs-target': '#collapseCategories', 'data-bs-toggle': 'collapse', href: '#'}
        %i.fa.fa-list
        %span= I18n.t('book_categories')
      #collapseCategories.collapse{'aria-labelledby': 'headingPages', 'data-bs-parent': '#accordionSidebar'}
        .bg-white.py-2.collapse-inner.rounded
          = link_to I18n.t('register_category'), new_category_path, class: 'collapse-item'
          = link_to I18n.t('view_all'), categories_path, class: 'collapse-item'
    %li.nav-item
      = link_to import_books_path, class: 'nav-link' do
        %i.fa.fa-file-import
        %span= I18n.t('import_books')
        %sup= I18n.t('csv')
  %hr.sidebar-divider.d-none.d-md-block
  .text-center.d-none.d-md-inline
    %button#sidebarToggle.rounded-circle.border-0{ onclick: 'general.toggleSidebar();' }

app/views/layouts/_topbar.html.haml
%nav.navbar.navbar-expand.navbar-light.bg-white.topbar.mb-4.static-top.shadow.pe-4
	.ms-2
		= link_to root_path(locale: 'pt-BR'), class: 'flag-language mx-1' do
			= image_tag 'https://i.ibb.co/1zpgj6Q/brasil-flag.png'
		= link_to root_path(locale: 'en'), class: 'flag-language mx-1' do
			= image_tag 'https://i.ibb.co/jGZGb3r/eua-flag.png'
	%ul.navbar-nav.ml-auto
		%li.nav-item.no-arrow.mx-1.dropdown
			%a.nav-link.dropdown-toggle{ 'data-bs-toggle': 'dropdown', role: 'button', 'aria-expanded': 'false' }
				%i.fas.fa-bell.fa-fw
				#badge.badge.badge-danger.badge-counter.box-notification{ style: set_visible }
					= @notifications.size
			%ul.dropdown-menu.dropdown-menu-end.shadow.animated--grow-in.dropdown-list
				%h6.dropdown-header
					= I18n.t('notifications_center')
				#container-notifications
					- if @notifications.size.zero?
						.text-center.mt-2{ id:'no-notif' }= I18n.t('no_notifications')
					- else
						= render @notifications
				= form_tag clean_all_notifications_path, remote: true, method: :post, onsubmit: 'general.cleanNotifications();' do
					%button.dropdown-item.text-center.small.text-gray-500{ type: 'submit' }= I18n.t('clean_all_notifications')
		%li.nav-item.dropdown.no-arrow
			%a#userDropdown.nav-link.dropdown-toggle{ 'aria-expanded': 'false', 'aria-haspopup': 'true', 'data-bs-toggle': 'dropdown', role: 'button' }
				%span.mr-2.d-none.d-lg-inline.text-gray-600.small
					= set_name
				.user-profile-logo
					%i.fa-regular.fa-user
			.dropdown-menu.dropdown-menu-right.shadow.animated--grow-in{ 'aria-labelledby': 'userDropdown' }
				= link_to edit_user_registration_path, class: 'dropdown-item' do		
					%i.fas.fa-user.fa-sm.fa-fw.mr-2.text-gray-400
					= I18n.t('edit_profile')
				.dropdown-divider
				= link_to destroy_user_session_path, method: :delete, class: 'dropdown-item' do
					%i.fas.fa-sign-out-alt.fa-sm.fa-fw.mr-2.text-gray-400
					Logout

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: 'text/html; charset=UTF-8', 'http-equiv': 'Content-Type' }
    %title Book System Online
    %meta{ content: 'width=device-width,initial-scale=1', name: 'viewport' }
    :javascript
      (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
      new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
      j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
      'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
      })(window,document,'script','dataLayer','GTM-T3PTN23');

    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body#page-top{ class: active_sidebar }
    %noscript
    %iframe{src: 'https://www.googletagmanager.com/ns.html?id=GTM-T3PTN23', height: 0, width: 0, style: "display:none;visibility:hidden"}

    = toastr_flash 
    #wrapper
      = render 'layouts/sidebar'
      #content-wrapper.d-flex.flex-column
        #content
          = render 'layouts/topbar'
          %div.px-5.mt-5
            = yield
        = render 'layouts/footer'
    = render 'layouts/scroll_top'

app/views/layouts/sign_in.html.haml
!!!
%html
  %head
    %meta{ content: 'text/html; charset=UTF-8', 'http-equiv': 'Content-Type' }
    %title Book System Online
    %meta{ content: 'width=device-width,initial-scale=1', name: 'viewport' }
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body.bg-gradient-primary
    = toastr_flash 
    .container
      .row.justify-content-center
        .col-xl-10.col-lg-12.col-md-9
          .card.o-hidden.border-0.shadow-lg.my-5
            .card-body.p-0
              .row
                .col-lg-6.sign-in-box
                  %div
                    Book System 
                    %br Online
                = yield